name: im_demo
description: Demo for IM Flutter

publish_to: "none"

version: 9.7.2

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  netease_roomkit: ^1.30.1
  nim_conversationkit_ui: ^9.7.2
  nim_chatkit_ui: ^9.7.2
  nim_teamkit_ui: ^9.7.2
  nim_contactkit_ui: ^9.7.2
  nim_searchkit_ui: ^9.7.2
  nim_chatkit_location: ^9.7.2
  yunxin_alog: ^2.0.0
  fluttertoast: ^8.2.4
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  provider: ^6.0.0
  flutter_screenutil: ^5.8.4
  fps_monitor: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
